### ISSUE TITLE
Start SNEO

### ISSUE THREAD

**Issue by songlunglinh** [kaitoy/sneo#1]
java -jar giane-jetty.war --httpPort 8080 --jmx.httpPort 8082 --jmx.rmiPort 1099
Error: Unable to access jarfile giane-jetty.war
can you help me, pls?

**Comment by kaitoy** [comment]
The error is just saying the giane-jetty.war file doesn't exist at the path specified by -jar option.
Are you sure you placed giane-jetty.war in the correct directory?
Can you tell me the exact command you executed?
Granting proper permissions to giane-jetty.war may solve the issue.
